const assert=require('node:assert/strict')
const {chromium}=require('../../desktop/node_modules/playwright-core')
;(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage();let signup, settingsSave
const data={revision:1,settings:{base_currency:'RWF',standard:'20',premium:'100',rates:{RWF:'1',USD:'1000'},rates_note:'Test rates',momo_number:'0786854200'},momo_number:'0786854200',plans:['RWF','USD'].flatMap(currency=>['free','standard','premium'].map((plan,i)=>({currency,plan,amount:String([0,20,100][i]/(currency==='USD'?1000:1)),amount_rwf:String([0,20,100][i])})))}
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.port==='5199')return route.continue();const json=body=>route.fulfill({json:body});if(u.pathname==='/subscription-plans')return json(data);if(u.pathname==='/users/register'){signup=route.request().postDataJSON();return json({user_id:99})}if(u.pathname==='/admin/subscription-plans'){settingsSave=route.request().postDataJSON();return json({...data,settings:settingsSave})}if(u.pathname==='/users/me')return json({user_id:1,full_name:'Admin',role:'admin'});return json([])})
await page.goto('http://localhost:5199/#login');await page.getByRole('button',{name:'Need an account? Create one'}).click();await page.getByLabel('Display currency').selectOption('USD');await page.getByRole('radio').nth(1).check();await page.getByText(/Pay 20 RWF by MoMo/).waitFor();await page.getByLabel('I have reviewed the yearly price and payment terms.').check();await page.getByLabel('Account field',{exact:true}).selectOption('it');await page.getByLabel('Account role',{exact:true}).selectOption('client');await page.getByPlaceholder('Enter your full name').fill('Test subscriber');await page.getByPlaceholder('Enter your email').fill('test@example.com');await page.getByPlaceholder('Enter your password').fill('Test-password');await page.getByRole('button',{name:'Create account',exact:true}).click();await page.getByText('Account created. You can now log in.').waitFor();assert.equal(signup.subscription.plan,'standard');assert.equal(signup.subscription.currency,'USD');assert.equal(signup.subscription.accepted_terms,true)
await page.evaluate(()=>{localStorage.setItem('access_token','mock');localStorage.setItem('user_id','1');localStorage.setItem('user_role','admin')});await page.goto('http://localhost:5199/#app');await page.reload();await page.getByRole('button',{name:'Subscriptions',exact:true}).click();await page.getByLabel('standard / year (RWF)').fill('30');await page.getByRole('button',{name:'Save subscription settings'}).click();await page.getByText('Subscription settings saved.').waitFor();assert.equal(settingsSave.standard,'30');console.log('PASS: converted signup quote, terms acceptance, saved selection, admin prices')
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1})

