export const homeCopy = {
  en: {
    home: 'Home', board: 'Sales board', how: 'How it works', enter: 'Open Simeon', login: 'Log in', join: 'Create an account',
    eyebrow: 'Built for the people who keep equipment working', title: 'Your experience.\nOur shared knowledge.',
    intro: 'Meet Simeon, your technician companion. Record repairs through conversation, learn from maintenance experience, and share equipment with the people who need it.',
    browse: 'Explore equipment', preview: 'A simpler way to record your work', question: 'What was found to be causing the problem?', answer: 'The pump seal was worn. I replaced it and tested the equipment.', follow: 'What parts did you use?', example: 'Example conversation',
    feature1: 'Talk through your work', detail1: 'Simeon guides you through a job card, one question at a time. Review your answers before saving.',
    feature2: 'Build shared knowledge', detail2: 'Capture successful maintenance work so useful experience can help the next technician.',
    feature3: 'Give equipment a new opportunity', detail3: 'Store an item with its photo and price, then choose when to post it to the sales board.',
    boardIntro: 'Equipment, posted by technicians.', boardDetail: 'Browse the latest published listings. Create an account to store and post your own items.',
    search: 'Search equipment or items', empty: 'No listings found.', emptyDetail: 'Try another search or come back as technicians post more items.',
    loading: 'Loading listings…', error: 'We couldn’t load the sales board. Please try again.', retry: 'Try again', more: 'Load more',
    seller: 'Posted by', details: 'View details', close: 'Close details', list: 'List your equipment',
    cta: 'Make your next repair part of something bigger.', ctaDetail: 'Bring your experience to Simeon. Start with a conversation.', languages: 'English · Kinyarwanda · Français · Kiswahili',
  },
  rw: {
    home: 'Ahabanza', board: 'Ibigurishwa', how: 'Uko bikora', enter: 'Fungura Simeon', login: 'Injira', join: 'Fungura konti',
    eyebrow: 'Ku bantu batuma ibikoresho bikomeza gukora', title: 'Ubunararibonye bwawe.\nUbumenyi dusangiye.',
    intro: 'Menya Simeon, umufasha wawe mu bya tekiniki. Andika isanwa mu kiganiro, wigire ku bunararibonye kandi usangize abandi ibikoresho bakeneye.',
    browse: 'Reba ibikoresho', preview: 'Uburyo bworoshye bwo kwandika akazi', question: 'Ni iki cyagaragaye ko gitera ikibazo?', answer: 'Agapira ka pompe kari gashaje. Naragasimbuye ngerageza igikoresho.', follow: 'Ni ibihe bice wakoresheje?', example: 'Urugero rw’ikiganiro',
    feature1: 'Vuga ibyo wakoze', detail1: 'Simeon ikuyobora mu kuzuza ifishi y’akazi, ikibazo kimwe kimwe. Suzuma ibisubizo mbere yo kubika.',
    feature2: 'Twubake ubumenyi dusangiye', detail2: 'Bika isanwa ryagenze neza kugira ngo ubunararibonye bufashe undi mutekinisiye.',
    feature3: 'Ha ibikoresho andi mahirwe', detail3: 'Bika ikintu, ifoto n’igiciro cyacyo, hanyuma uhitemo igihe cyo kugitangaza.',
    boardIntro: 'Ibikoresho byatangajwe n’abatekinisiye.', boardDetail: 'Reba ibimaze gutangazwa. Fungura konti kugira ngo ubike kandi utangaze ibyawe.',
    search: 'Shakisha ibikoresho cyangwa ibintu', empty: 'Nta byatangajwe bibonetse.', emptyDetail: 'Gerageza gushakisha ibindi cyangwa ugaruke nyuma.',
    loading: 'Birimo gutegurwa…', error: 'Ntitwashoboye kubona ibigurishwa. Ongera ugerageze.', retry: 'Ongera ugerageze', more: 'Reba ibindi',
    seller: 'Byatangajwe na', details: 'Reba ibisobanuro', close: 'Funga ibisobanuro', list: 'Tangaza ibikoresho byawe',
    cta: 'Isanwa ryawe rizafashe n’abandi.', ctaDetail: 'Zana ubunararibonye bwawe kuri Simeon. Tangira ikiganiro.', languages: 'English · Kinyarwanda · Français · Kiswahili',
  },
  fr: {
    home: 'Accueil', board: 'Annonces', how: 'Comment ça marche', enter: 'Ouvrir Simeon', login: 'Connexion', join: 'Créer un compte',
    eyebrow: 'Pour celles et ceux qui font fonctionner les équipements', title: 'Votre expérience.\nNotre savoir partagé.',
    intro: 'Découvrez Simeon, votre compagnon technique. Consignez vos réparations par conversation, apprenez des interventions et partagez vos équipements.',
    browse: 'Explorer les équipements', preview: 'Une façon plus simple de documenter votre travail', question: 'Quelle était la cause du problème ?', answer: 'Le joint de la pompe était usé. Je l’ai remplacé et testé l’équipement.', follow: 'Quelles pièces avez-vous utilisées ?', example: 'Exemple de conversation',
    feature1: 'Racontez votre intervention', detail1: 'Simeon vous guide, une question à la fois. Vérifiez vos réponses avant d’enregistrer la fiche.',
    feature2: 'Construisez un savoir partagé', detail2: 'Consignez les interventions réussies pour aider le prochain technicien.',
    feature3: 'Offrez une nouvelle vie aux équipements', detail3: 'Enregistrez un article avec sa photo et son prix, puis choisissez quand publier l’annonce.',
    boardIntro: 'Des équipements proposés par des techniciens.', boardDetail: 'Consultez les dernières annonces. Créez un compte pour enregistrer et publier vos articles.',
    search: 'Rechercher un équipement ou un article', empty: 'Aucune annonce trouvée.', emptyDetail: 'Essayez une autre recherche ou revenez plus tard.',
    loading: 'Chargement des annonces…', error: 'Impossible de charger les annonces. Veuillez réessayer.', retry: 'Réessayer', more: 'Afficher plus',
    seller: 'Publié par', details: 'Voir les détails', close: 'Fermer les détails', list: 'Publier votre équipement',
    cta: 'Votre prochaine réparation peut aider d’autres techniciens.', ctaDetail: 'Partagez votre expérience sur Simeon. Commencez par une conversation.', languages: 'English · Kinyarwanda · Français · Kiswahili',
  },
  sw: {
    home: 'Mwanzo', board: 'Matangazo', how: 'Jinsi inavyofanya kazi', enter: 'Fungua Simeon', login: 'Ingia', join: 'Fungua akaunti',
    eyebrow: 'Kwa watu wanaowezesha vifaa kuendelea kufanya kazi', title: 'Uzoefu wako.\nMaarifa yetu ya pamoja.',
    intro: 'Kutana na Simeon, mwenzako wa kiufundi. Rekodi matengenezo kupitia mazungumzo, jifunze kutokana na uzoefu na shiriki vifaa.',
    browse: 'Tazama vifaa', preview: 'Njia rahisi ya kurekodi kazi yako', question: 'Ni nini kilichosababisha tatizo?', answer: 'Muhuri wa pampu ulikuwa umechakaa. Niliubadilisha na kujaribu kifaa.', follow: 'Ulitumia vipuri gani?', example: 'Mfano wa mazungumzo',
    feature1: 'Eleza kazi yako', detail1: 'Simeon hukuongoza swali moja baada ya jingine. Kagua majibu kabla ya kuhifadhi kadi ya kazi.',
    feature2: 'Jenga maarifa ya pamoja', detail2: 'Rekodi matengenezo yaliyofanikiwa ili uzoefu uwasaidie mafundi wengine.',
    feature3: 'Vipe vifaa nafasi mpya', detail3: 'Hifadhi kitu pamoja na picha na bei, kisha uchague wakati wa kuchapisha tangazo.',
    boardIntro: 'Vifaa vilivyochapishwa na mafundi.', boardDetail: 'Tazama matangazo mapya. Fungua akaunti ili uhifadhi na uchapishe vitu vyako.',
    search: 'Tafuta vifaa au vitu', empty: 'Hakuna matangazo yaliyopatikana.', emptyDetail: 'Jaribu utafutaji mwingine au urudi baadaye.',
    loading: 'Inapakia matangazo…', error: 'Imeshindwa kupakia matangazo. Tafadhali jaribu tena.', retry: 'Jaribu tena', more: 'Onyesha zaidi',
    seller: 'Imechapishwa na', details: 'Tazama maelezo', close: 'Funga maelezo', list: 'Chapisha kifaa chako',
    cta: 'Matengenezo yako yajayo yawasaidie wengine.', ctaDetail: 'Leta uzoefu wako kwa Simeon. Anza na mazungumzo.', languages: 'English · Kinyarwanda · Français · Kiswahili',
  },
}
