export const landingCopy = {
  en: {
    eyebrow: 'FOUR FIELDS. ONE CONNECTED WORKSPACE.', title: 'Keep work moving.\nFind what you need.',
    intro: 'Simeon brings engineers or technicians, stores and clients together. Record maintenance, manage your stock, and connect with people looking for the right equipment.',
    how: 'Choose your role', boardIntro: 'Find your next piece of equipment.', boardDetail: 'Explore equipment and spare parts posted by engineers or technicians and stores. Filter by field, then sign in to send a request.',
    list: 'Open your workspace', cta: 'A place for every part of the work.', ctaDetail: 'Choose your field. Choose your role. Make Simeon your workspace.',
    fields: 'Your field. Your community.', fieldDetail: 'Medical, IT, Electrical and Mechanical — explore listings across all four fields.',
    roleDetail: 'Start with the tools that match what you do.', workspace: 'A workspace built around your role',
    technician: 'Record job cards with Simeon, find maintenance help and share equipment.',
    store: 'Manage stock, publish items with photos and prices, and respond to requests.',
    client: 'Browse equipment and spare parts, request items and follow your requests.',
    offline: 'Android: save drafts offline and sync when you reconnect.',
  },
  rw: {
    eyebrow: 'INZEGO ENYE. URUBUGA RUMWE.', title: 'Komeza akazi.\nBona ibyo ukeneye.',
    intro: 'Simeon ihuza abatekinisiye, amaduka n’abakiriya. Andika isanwa, ucunge ububiko kandi uhure n’abakeneye ibikoresho.',
    how: 'Hitamo uruhare rwawe', boardIntro: 'Bona igikoresho ukeneye.', boardDetail: 'Reba ibikoresho byatangajwe n’abatekinisiye n’amaduka. Hitamo urwego, winjire wohereze ubusabe.',
    list: 'Fungura urubuga rwawe', cta: 'Umwanya wa buri wese mu kazi.', ctaDetail: 'Hitamo urwego n’uruhare rwawe. Korana na Simeon.',
    fields: 'Urwego rwawe. Abakorana nawe.', fieldDetail: 'Ubuvuzi, ikoranabuhanga, amashanyarazi n’ubukanishi — reba ibikoresho mu nzego zose.',
    roleDetail: 'Tangira n’ibikoresho bijyanye n’akazi kawe.', workspace: 'Urubuga rujyanye n’uruhare rwawe',
    technician: 'Andika amafishi hamwe na Simeon, ubone ubufasha mu gusana kandi usangize abandi ibikoresho.',
    store: 'Cunga ububiko, tangaza ibikoresho bifite amafoto n’ibiciro kandi usubize ubusabe.',
    client: 'Reba ibikoresho, ubyoherezeho ubusabe kandi ukurikirane ubusabe bwawe.',
    offline: 'Android: bika ibisubizo nta interineti, ubyohereze igarutse.',
  },
  fr: {
    eyebrow: 'QUATRE DOMAINES. UN ESPACE COMMUN.', title: 'Faites avancer le travail.\nTrouvez le bon équipement.',
    intro: 'Simeon réunit techniciens, magasins et clients. Documentez la maintenance, gérez votre stock et rencontrez les personnes qui recherchent vos équipements.',
    how: 'Choisir votre rôle', boardIntro: 'Trouvez votre prochain équipement.', boardDetail: 'Découvrez les équipements et pièces proposés par les techniciens et magasins. Filtrez par domaine et connectez-vous pour envoyer une demande.',
    list: 'Ouvrir votre espace', cta: 'Une place pour chaque rôle.', ctaDetail: 'Choisissez votre domaine et votre rôle. Travaillez avec Simeon.',
    fields: 'Votre domaine. Votre communauté.', fieldDetail: 'Médical, informatique, électricité et mécanique : explorez les annonces des quatre domaines.',
    roleDetail: 'Commencez avec les outils adaptés à votre activité.', workspace: 'Un espace adapté à votre rôle',
    technician: 'Créez vos fiches avec Simeon, trouvez de l’aide technique et partagez vos équipements.',
    store: 'Gérez le stock, publiez des articles avec photos et prix, et répondez aux demandes.',
    client: 'Consultez les équipements et pièces, envoyez des demandes et suivez leur évolution.',
    offline: 'Android : enregistrez hors ligne et synchronisez au retour d’internet.',
  },
  sw: {
    eyebrow: 'SEKTA NNE. NAFASI MOJA YA KAZI.', title: 'Endeleza kazi.\nPata unachohitaji.',
    intro: 'Simeon inaunganisha mafundi, maduka na wateja. Rekodi matengenezo, simamia hifadhi na ungana na watu wanaotafuta vifaa.',
    how: 'Chagua jukumu lako', boardIntro: 'Pata kifaa chako kinachofuata.', boardDetail: 'Tazama vifaa na vipuri vilivyotangazwa na mafundi na maduka. Chuja kwa sekta kisha ingia kutuma ombi.',
    list: 'Fungua nafasi yako', cta: 'Nafasi kwa kila jukumu.', ctaDetail: 'Chagua sekta na jukumu lako. Fanya kazi na Simeon.',
    fields: 'Sekta yako. Jamii yako.', fieldDetail: 'Matibabu, teknolojia ya habari, umeme na mitambo — tazama matangazo katika sekta zote nne.',
    roleDetail: 'Anza na zana zinazolingana na kazi yako.', workspace: 'Nafasi inayolingana na jukumu lako',
    technician: 'Rekodi kadi na Simeon, pata msaada wa matengenezo na shiriki vifaa.',
    store: 'Simamia hifadhi, tangaza bidhaa zenye picha na bei, na ujibu maombi.',
    client: 'Tazama vifaa na vipuri, tuma maombi na ufuatilie maombi yako.',
    offline: 'Android: hifadhi rasimu bila intaneti na utume intaneti ikirudi.',
  },
}
