// Separate inventory records; one medicine batch or equipment model/asset per entry.
const f = (key, label, required = false, type = 'text', options) => ({ key, label, required, type, options })
const stock = [f('quantity', 'How many stock units are available?', true, 'number'), f('unit', 'What is the stock and selling unit? For example: box of 100, bottle of 60, or one device.', true), f('manufacturer', 'Who is the manufacturer?', true)]
const location = [f('storage_location', 'Where is this stock stored? Shelf, bin, or room.'), f('supplier', 'Who supplied this stock?'), f('received_date', 'When was it received?', false, 'date'), f('reorder_level', 'At what quantity should you reorder?', false, 'number')]
const sale = [f('description', 'Add any product notes or specifications to show buyers.', true, 'textarea'), f('price', 'What is the selling price per stock unit?', true, 'price'), f('currency', 'Which currency?', true, 'select', ['RWF', 'USD', 'EUR', 'KES', 'TZS', 'UGX']), f('photo_data', 'Upload a clear product or label photo.', true, 'photo')]
export const medicalRecordingFields = {
  pharmacy: [f('name', 'What is the medicine brand or product name?', true), f('generic_name', 'What is the generic name / active ingredient?', true), f('strength', 'What strength is printed on the label? For example: 500 mg or 125 mg/5 mL.', true), f('dosage_form', 'What is the dosage form?', true, 'select', ['Tablet', 'Capsule', 'Oral solution', 'Suspension', 'Injection', 'Cream / ointment', 'Drops', 'Inhaler', 'Powder', 'Other']), f('route', 'What route is stated on the product label?'), f('pack_size', 'What is the pack size? For example: 10 blisters of 10 tablets.', true), ...stock, f('batch_number', 'What is the batch / lot number?', true), f('manufacture_date', 'What is the manufacture date, if known?', false, 'date'), f('expiry_date', 'What is the expiry date for this batch?', true, 'date'), f('storage_conditions', 'What storage conditions are printed on the label?', true), f('prescription_status', 'What is the recorded dispensing classification?', false, 'select', ['Prescription required', 'Non-prescription', 'Not recorded']), ...location, ...sale],
  consumables: [f('name', 'What is the medical consumable name?', true), f('product_code', 'What is the catalogue / product code?'), f('size_specification', 'What size, gauge, capacity, or dimensions identify this product?', true), f('material', 'What material is it made from?'), f('sterility', 'What is its labelled sterility status?', true, 'select', ['Sterile', 'Non-sterile', 'Not recorded']), f('single_use', 'What use type is stated on the label?', true, 'select', ['Single-use', 'Reusable', 'Not recorded']), f('pack_size', 'How many pieces are in each pack?', true), ...stock, f('batch_number', 'What is the batch / lot number?', true), f('expiry_date', 'What is the expiry date, if applicable?', false, 'date'), f('storage_conditions', 'What storage conditions are required?'), ...location, ...sale],
  biomedical: [f('name', 'What is the biomedical equipment name?', true), f('equipment_type', 'What type of equipment is it? For example: patient monitor, centrifuge, or ultrasound.', true), ...stock, f('model', 'What is the equipment model?', true), f('serial_number', 'What is the serial number? Use one record per serialized device.'), f('asset_tag', 'What is the asset / inventory tag?'), f('condition', 'What is its condition?', true, 'select', ['New', 'Used - working', 'Refurbished', 'Needs repair', 'For parts']), f('power_requirements', 'What are the voltage, frequency, and power requirements?'), f('accessories', 'Which probes, cables, accessories, or manuals are included?', false, 'textarea'), f('last_service_date', 'When was it last serviced?', false, 'date'), f('next_service_date', 'When is the next service due?', false, 'date'), f('calibration_due_date', 'When is calibration due, if applicable?', false, 'date'), f('warranty_end', 'When does the warranty end?', false, 'date'), ...location, ...sale],
}

export function medicalPayload(category, answers) {
  const { name, description, price, currency, photo_data, ...details } = answers
  return { name, description, price, currency, photo_data, medical_category: category, medical_details: { ...Object.fromEntries(Object.entries(details).filter(([, value]) => value !== null)), record_version: 2 } }
}
